id: PB6326D12
initial_creation_type: input
source_metadata:
  title: Swift Rebirth Prayers
  language: en
  description: 'A selection of prayers for the swift rebirth (myur byon gsol ’debs)
    of prominent individuals (arranged alphabetically by subject):'
  volume:
    65d24afe13b945428eddb1b54f5e62db:
      title: 'The Swift Fulfilment of Wishes: A Prayer for the Swift Return of the
        Supreme Tulku of the Fifth Drubwang Dzogchen Rinpoche'
      parent: Fifth Dzogchen Rinpoche
    33236d75d06a42129b0b520ffa779332:
      title: Prayer for Swift Rebirth of the Fourth Dodrupchen Rinpoche
      parent: Fourth Dodrupchen Rinpoche
    d2a0681f8978419b9a69d254ef14a90d:
      title: Prayer for Swift Rebirth of the Fourth Dodrupchen Rinpoche, Tupten Trinlé
        Palzangpo
      parent: Fourth Dodrupchen Rinpoche
    32b342daaae94d209d1b621530a0e421:
      title: Prayer for the Swift Rebirth of the Fourth Dodrupchen Rinpoche
      parent: Fourth Dodrupchen Rinpoche
    f5d502722a4048058162fb0ba498fe7c:
      title: A Prayer for the Swift Return of the Fourth Kyabje Dodrupchen Rinpoche
      parent: Fourth Dodrupchen Rinpoche
    dc0043fdb1104c938b17e97f24af9bc4:
      title: 'The Moonlight of Auspiciousness: A Yearning Prayer to the Noble and
        Glorious Guru Combined with an Aspiration for His Swift Return'
      parent: Gyurme Tsewang Gyatso
    abd11f12b04f42d1bb3065745a75cda4:
      title: Prayer to Kongtrul Yönten Gyatso
      parent: Jamgön Kongtrul Lodrö Thaye
    184b4ce9548f4781855e8aec2e84b55d:
      title: Prayer for the Swift Rebirth of Jamyang Khyenrab Tayé
      parent: Jamyang Khyenrab Tayé
    f71303bbbcaf4838b78ad8c9a38c4f11:
      title: Lamenting Prayer to Jamyang Chökyi Lodrö
      parent: Jamyang Khyentse Chökyi Lodrö
    ac1732fec363424a804812133e95d902:
      title: 'Wondrous Light of the Moon: A Prayer for the Swift Appearance of the
        Supreme Tulku of Vajradhara'
      parent: Jamyang Loter Wangpo
    bf6c67269b004441b94e3c435c872fb3:
      title: 'The Swift Fulfilment of Wishes: Prayer for the Swift Appearance of the
        Supreme Tulku of the Mañjughoṣa Guru'
      parent: Katok Situ Chökyi Gyatso
    4266108ae8a248069fde4c02b02da90e:
      title: 'Cymbals to Invoke a Compassionate Response: A Prayer for Swift Rebirth
        of Khandro Tsering Chödrön'
      parent: Khandro Tsering Chödrön
    3039fed37e6e4c1e833cfa2b6c595dfe:
      title: 'The Swift Infusion of Blessings: A Lament and Prayer to Invoke the Wisdom
        Mind of Khenchen Vāgindra on the Occasion of His Passing into the Great Peace
        of the Dharmadhātu'
      parent: Ngawang Samten Lodrö
    60c45179df984137b9d5ade65ce0c649:
      title: A Prayer for the Swift Rebirth of Tenpai Nyima Rinpoche
      parent: Tenpai Nyima Rinpoche
    d361883e16514ee48adbe444c2551e98:
      title: 'The Tambura of Devotion: A Prayer for the Swift Appearance of the Supreme
        Tulku of the All-Seeing Conqueror and Cardinal Guardian of the Land of Snows'
      parent: Thirteenth Dalai Lama
    10e532bf707a4325b100382aa4a83f7e:
      title: Prayer for the Swift Rebirth of Kyabjé Trulshik Rinpoche
      parent: Trulshik Rinpoche
created_at: '2022-03-01T05:59:59.955416'
last_modified_at: '2022-03-01T05:59:59.955422'
